image:
  file: .gitpod/Dockerfile
   
tasks:
  - name: Create DB Schema
    init: > 
      mysql < data/schema.sql && 
      gp sync-done schema

  - name: Spring
    init: >
      ./gradlew bootRun -x test &&
      gp sync-await schema

  - name: Dump Chart Data
    init: >
      mysql < data/chart.sql &&
      gp sync-await schema && 
      gp sync-done dump_chart

  - name: Dump Hit Data
    init: >
      mysql < data/hit.sql && 
      gp sync-await dump_chart

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot