image:
  file: .gitpod/Dockerfile
   
tasks:
  - name: Create DB Schema
    init: > 
      mysql < data.schema.sql && 
      gp sync-done schema

  - name: Spring
    init: >
      ./gradlew bootRun -x test &&
      gp sync-await schema

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot