image:
  file: .gitpod/Dockerfile
   
tasks:
  - name: Create DB Schema
    init: > 
      mysql < data/schema.sql && 
      gp sync-done schema

  - name: Spring
    init: gp sync-await schema
    command: ./gradlew bootRun -x test 

  - name: Import Data
    init: gp sync-await schema
    command: mysql < data/chart.sql && mysql < data/hit.sql   

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot