image:
  file: .gitpod/Dockerfile
   
tasks:
  - name: Do stuff \o/
    init: > 
      cp -f .gitpod/nginx/nginx.conf /etc/nginx/nginx.conf &&
      service start nginx && 
      while ! (mysqladmin ping 2> /dev/null); do sleep 2; echo 'Waiting for mySQL... sit tight!'; done && 
      mysql < data/schema.sql && 
      mysql < data/chart.sql && 
      mysql < data/hit.sql &&
      ./gradlew bootRun -x test 

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
- port: 8082
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot